# Generated by Django 5.0.6 on 2024-05-17 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField()),
                ('apellido', models.CharField()),
                ('posicion', models.CharField()),
                ('usuario', models.CharField()),
                ('contraseña', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id_posicion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField()),
            ],
        ),
    ]
