# Generated by Django 5.0.6 on 2024-05-29 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersTenants', '0002_alter_empleado_apellido_alter_empleado_contraseña_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='posicion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UsersTenants.posicion'),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='nombre',
            field=models.CharField(unique=True),
        ),
    ]
