# Generated by Django 5.0.6 on 2024-05-29 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersTenants', '0004_alter_posicion_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioTipo',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InventarioConsumible',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('proveedor', models.CharField(max_length=150)),
                ('lote', models.IntegerField()),
                ('caducidad', models.DateField()),
                ('id_tipo', models.ForeignKey(default='Sin Tipo', on_delete=django.db.models.deletion.SET_DEFAULT, to='UsersTenants.inventariotipo')),
            ],
        ),
    ]
