# Generated by Django 5.0.6 on 2024-05-30 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersTenants', '0007_alter_inventariotipo_id_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoTipo',
            fields=[
                ('id_tipo', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InventarioEquipo',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('marca', models.CharField(max_length=150)),
                ('modelo', models.CharField(max_length=150)),
                ('Numero_serie', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('id_tipo', models.ForeignKey(default='Sin Tipo', on_delete=django.db.models.deletion.SET_DEFAULT, to='UsersTenants.equipotipo')),
            ],
        ),
    ]
