# Generated by Django 5.0.6 on 2024-05-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersTenants', '0010_alter_paciente_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono_emergencia',
            field=models.CharField(),
        ),
    ]
