# Generated by Django 5.0.6 on 2024-05-30 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersTenants', '0012_remove_paciente_edad_paciente_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedimiento',
            fields=[
                ('id_procedimiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id_consulta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_termino', models.TimeField()),
                ('dentista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsersTenants.empleado')),
                ('paciente', models.ForeignKey(default='ELIMINADO', on_delete=django.db.models.deletion.SET_DEFAULT, to='UsersTenants.paciente')),
                ('procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsersTenants.procedimiento')),
            ],
        ),
    ]
