# Generated by Django 5.0.6 on 2024-05-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersTenants', '0013_procedimiento_alter_paciente_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='finalizada',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
