# Generated by Django 5.0.6 on 2024-05-30 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersTenants', '0015_alter_consulta_dentista_alter_consulta_procedimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='dentista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UsersTenants.empleado'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UsersTenants.paciente'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='procedimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UsersTenants.procedimiento'),
        ),
    ]
