# Generated by Django 5.0.6 on 2024-05-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='nombre_clinica',
            field=models.CharField(null=True),
        ),
    ]
