# Generated by Django 5.0.6 on 2024-05-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0002_client_nombre_clinica'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='fecha_limite',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='pagado',
            field=models.BooleanField(null=True),
        ),
    ]
